config/routes.rb
=begin
FizzbuzzSample::Application.routes.draw do
  get 'favorites/create'

  namespace :api, defaults: { format: :json } do 
    scope module: :v1 do 
        get 'fizzbuzz/index'
        #post 'fizzbuzz/index'
        #resources :fizzbuzz
    end
  end
end

=end
Rails.application.routes.draw do
  get 'favorites/create'

  get 'fizzbuzz/index'
  root to: 'fizzbuzz#index'
  resources  :favorites, only: [:create, :destroy]
  namespace :api do  
    namespace :v1 do
      resources :fizzbuzzapi, only: :index
      #get 'fizzbuzzapi/index'
      resources  :favoritesapi, only: [:index, :create, :destroy]

    end
  end  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/controllers/api/v1/favoritesapi_controller.rb
module Api::V1
  class FavoritesapiController < ApplicationController
    def index
      @favorites=Favorite.all
      if @favorites
        render json: {}, status: 200
      else
        render json: {error: "Favorite could not be deleted."}, status: 422
      end
    end
    # POST /favorites.json
    def create
      favorite= params[:favorite_id]
      @favorite=Favorite.new(number: favorite)
      respond_to do |format|
        if @favorite.save
          format.json { render json: {}, status: 200}
        else
          format.json { render json: @favorite.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /favorites/1.json
    def destroy
      @favorite = Favorite.find_by_number(params[:id])
      if !@favorite.nil? && @favorite.destroy 
        render json: {}, status: 200
        # Rails is told explicitly what to render
      else
        render json: {error: "Favorite could not be deleted."}, status: 422
      end
    end

  end
end

app/controllers/api/v1/fizzbuzzapi_controller.rb
module Api::V1
  class FizzbuzzapiController < ApplicationController

  #FIXME remove duplication
  
  include FizzBuzz

  # POST /v1/events
  def create
    render json: params.to_json
  end

  DEF_MIN = 1
  DEF_MAX = 100
  MAX=100_000_000_000
  def index
    #Allow parameters ?max=100&min=1&per_page=10
    max = params[:max]; min = params[:min]
    #set defaults
    # set it here instead of creating a class and attr_accessor
    min ||= DEF_MIN;   max ||= DEF_MAX
    max=MAX if max.to_i>MAX 
    range = min.to_i..max.to_i

    #calculate fizzbuzz over the range
    #make a hash where the number is the key and fizzbuzz is the value
    #fizzbuzz = range.map{|n| fizzbuzz(n)}
    fizz_hash={}
    range.each{|n| fizz_hash[n] = fizzbuzz(n)}

    render json: fizz_hash.to_json
  end


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: :destroy
  
  # POST /favorites
  # POST /favorites.json
  def create
    favorite= params[:favorite_id]
    @favorite=Favorite.new(number: favorite)
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to :back, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Favorite was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def set_favorite
    @favorite = Favorite.find_by_number(params[:favorite_id])
  end


end

app/controllers/fizzbuzz_controller.rb
class FizzbuzzController < ApplicationController
  include FizzBuzz

  DEF_MIN = 1
  DEF_MAX = 100
  MAX=100_000_000_000
  def index
    #Allow parameters ?max=100&min=1&per_page=10
    max = params[:max]; min = params[:min]
    per_page=params[:per_page]

    #set defaults
    # set it here instead of creating a class and attr_accessor
    per_page||=100
    min ||= DEF_MIN;   max ||= DEF_MAX
    max=MAX if max.to_i>MAX 
    range = min.to_i..max.to_i

    #calculate fizzbuzz over the range
    #make a hash where the number is the key and fizzbuzz is the value
      #paginate supports arrays, so use a multi val array
    #fizzbuzz = range.map{|n| fizzbuzz(n)}
    fizz_hash=[]
    range.each{|n| fizz_hash << [n,fizzbuzz(n)]}

    @fizzbuzz = fizz_hash.paginate(:page => params[:page], :per_page =>per_page.to_i)

    
    # grab the favorites
    # make them into a hash, so you don't have to perform a full lookup
    favorites=Favorite.all.pluck(:number)
    @favorites={}
    favorites.each{|v| @favorites[v] = true }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/fizzbuzz_helper.rb
module FizzbuzzHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/fizzbuzz/index.html.erb
<div class="row">
<h1>FizzBuzz Example</h1>
<table class="table">
<% @fizzbuzz.each do |original,fizzbuzz| %>
	<% @favorites[original.to_i] ? active="active" : active=false %>
		<tr class="<%=active%>">
		 	<td><%= fizzbuzz %></td>
			<td>
			<!-- <%=@favorites.inspect %> -->
				<% if !active %>
					<%= link_to 'Favorite', favorites_path(favorite_id: original.to_i), method: :post %>
				<%else %>
					<%= link_to 'Un-favorite', favorite_path(id:original.to_i, favorite_id: original.to_i), :method => :delete %>
		 		<%end%>
		 	</td>			
		</tr>
<% end %>
</table>
<div class="center">
	<%= will_paginate @fizzbuzz %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FizzbuzzSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>  
</head>
<body>
<div class="container">
<div class="row"
<p class="notice"><%= notice ? notice : raw("<br>") %></p>
</div>
<%= yield %>
</div>
</body>
</html>